# Generated by Django 5.0.0 on 2024-01-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="ティッカーシンボル"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="銘柄名")),
                (
                    "exchange",
                    models.CharField(default="TSE", max_length=10, verbose_name="市場"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "株式銘柄",
                "verbose_name_plural": "株式銘柄",
            },
        ),
        migrations.CreateModel(
            name="StockPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                (
                    "open_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="始値"
                    ),
                ),
                (
                    "high_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="高値"
                    ),
                ),
                (
                    "low_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="安値"
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="終値"
                    ),
                ),
                ("volume", models.BigIntegerField(verbose_name="出来高")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "株価データ",
                "verbose_name_plural": "株価データ",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="StockPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prediction_date", models.DateField(verbose_name="予測日")),
                (
                    "predicted_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="予測価格"
                    ),
                ),
                ("confidence", models.FloatField(default=0.0, verbose_name="信頼度")),
                (
                    "method",
                    models.CharField(
                        default="移動平均", max_length=50, verbose_name="予測手法"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "株価予想",
                "verbose_name_plural": "株価予想",
                "ordering": ["-prediction_date"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="stockprice",
            unique_together={("stock", "date")},
        ),
    ]
